name: CI-CD                
on:                        
  push:                    
    branches: ["main"]     
  workflow_dispatch:

jobs:                      
  CI:                      
    runs-on: ubuntu-latest 
    steps:                 
      - name: Obter Código
        uses: actions/checkout@v4.2.2
      - name: Docker Login
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Construção e envio da imagem Docker
        uses: docker/build-push-action@v6.15.0
        with:
          context: ./src
          push: true
          file: ./src/Dockerfile
          tags: fmossri/desafio-fake-shop:v${{ github.run_number }}
  CD:
    needs: [CI]
    runs-on: ubuntu-latest
    steps:
      - run: echo "Obter código"
      - run: echo "Configurar o kubeconfig"
      - run: echo "Executar o apply"
